#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 20 13:41:05 2017
Author: Peiyong Jiang : jiangpeiyong@impcas.ac.cn
Function:


"""

import numpy as np


def Lambda(a,b,g,e):
    arg_2agb=(2.*a)**2+(g-b)**2
    arg_2agb_R=np.sqrt(arg_2agb)
    arg_gb=g+b
    arg_2e=2.*e
    
    lambda_1=(arg_gb-arg_2agb_R)/arg_2e
    lambda_2=(arg_gb+arg_2agb_R)/arg_2e
    return np.array([[lambda_1,0],[0,lambda_2]])






